pipeline {
  agent {
    label 'docker-image'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '60'))
  }

  parameters {
    string name: 'version',
    defaultValue: 'dev',
    description: 'version to analyze (dev, nightly, nightly-10, sprint, 8.0, 10.0, 11.2, ...)',
    trim: true
  }

  stages {
    stage('scouting') {
      steps {
        script {
          def version = params.version;
          currentBuild.description = "version: ${version}"

          def tags = [version]
          if (version == 'dev' || version == 'sprint' || version == 'nightly') {
            tags = [version, version + '-slim', version + '-alpine', version + '-alpine-slim']
          }
          if (version == '12.0' || version == 'nightly-12.0') {
            tags = [version, version + '-slim', version + '-alpine', version + '-alpine-slim']
          }

          for (def tag : tags) {
            dockerScoutAnalyze(tag);
            archiveArtifacts 'report/*.json'
            recordIssues sourceCodeRetention: 'NEVER', tools: [sarif(pattern: 'report/sarif.json')], qualityGates: [[threshold: 1, type: 'TOTAL']]

            def env = dockerScoutEnvFrom(tag);
            dockerScoutCompare(tag, env);
            dockerScoutRecordInEnv(tag, env);
          }

          def scoutHref = "https://scout.docker.com/reports/org/axonivy/overview?stream=environment%3A${env}"
          currentBuild.description = "version: ${version} <a href='${scoutHref}'>docker-scout</a>"
        }
      }
    }
  }
}

def dockerScoutAnalyze(String tag) {
  withCredentials([usernamePassword(credentialsId: 'docker.io', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
    sh "docker run -t ${dockerLoginAsEnv()} " +
       "${dockerScoutContainer()} cves ${axonivyEngineImageUrl(tag)} " +
       "--ignore-base --locations"

    sh "mkdir -p ${env.WORKSPACE}/report"
    sh "docker run -t -v ${env.WORKSPACE}/report/:/report/ ${dockerLoginAsEnv()} " +
        "${dockerScoutContainer()} cves ${axonivyEngineImageUrl(tag)} " +
        "--ignore-base --only-fixed --locations --format sarif --output /report/sarif.json"

    sh "docker run -t -v ${env.WORKSPACE}/report/:/report/ ${dockerLoginAsEnv()} " +
        "${dockerScoutContainer()} sbom ${axonivyEngineImageUrl(tag)} " +
        "--format cyclonedx --output /report/bom.json"

    uploadBOM(projectName: 'axonivy/axonivy-engine', projectVersion: tag, bomFile: 'report/bom.json')
  }
}

def dockerScoutCompare(String tag, String env) {
  withCredentials([usernamePassword(credentialsId: 'docker.io', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
    catchError(buildResult: 'UNSTABLE', stageResult: 'UNSTABLE') {
      sh "docker run -t ${dockerLoginAsEnv()} " +
         "${dockerScoutContainer()} compare ${axonivyEngineImageUrl(tag)} " + 
         "--exit-on vulnerability,policy --only-package-type maven,npm --to-env ${env} --org axonivy"
    }
  }
}

def dockerScoutRecordInEnv(String tag, String env) {
  withCredentials([usernamePassword(credentialsId: 'docker.io-axonivyinfo', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
    sh 'docker run -t -e DOCKER_SCOUT_HUB_USER=$DOCKER_USER -e DOCKER_SCOUT_HUB_PASSWORD=$DOCKER_PASS ' +
       "${dockerScoutContainer()} env ${env} --org axonivy ${axonivyEngineImageUrl(tag)}"
  }
}

def dockerLoginAsEnv() {
  return '-e DOCKER_SCOUT_HUB_USER=$DOCKER_USER -e DOCKER_SCOUT_HUB_PASSWORD=$DOCKER_PASS -e DOCKER_SCOUT_REGISTRY_USER=$DOCKER_USER -e DOCKER_SCOUT_REGISTRY_PASSWORD=$DOCKER_PASS'
}

def dockerScoutContainer() {
  return sh (script: "cat docker-scout/Dockerfile.scout", returnStdout:true).trim().replaceFirst(/^FROM\s+/, '')
}

def axonivyEngineImageUrl(String tag) {
  return 'registry://axonivy/axonivy-engine:' + tag
}

def dockerScoutEnvFrom(String tag) {
  return version.replace('.0', '').replace('.', '-');
}
